language: R
sudo: required
warnings_are_errors: false
r_packages:
  - rmarkdown
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: 'likert_1.3.4.tar.gz'
  skip_cleanup: true
  on:
    tags
